import { TaskList } from "@/apis/group/type";

export const MOCK_TASKLISTS: TaskList[] = [
  {
    tasks: [
      {
        id: 0,
        name: '할 일 목록 1',
        updatedAt: '2026-06-01',
        displayIndex: 0,
        date: '2026-06-01',
        commentCount: 0,
        deletedAt: null,
        description: '설명',
        doneAt: null,
        doneBy: null,
        frequency: 'ONCE',
        recurringId: 1,
        startDate: '2026-06-01',
        writer: {
          id: 0,
          image: '',
          nickname: '',
        },
      },
      {
        id: 1,
        name: '할 일 목록 2',
        updatedAt: '2026-06-01',
        displayIndex: 1,
        date: '2026-06-01',
        commentCount: 3,
        deletedAt: null,
        description: '설명',
        doneAt: '2026-06-01',
        doneBy: {
          user: {
            id: 0,
            image: '',
            nickname: '',
          },
        },
        frequency: 'ONCE',
        recurringId: 1,
        startDate: '2026-06-01',
        writer: {
          id: 0,
          image: '',
          nickname: '',
        },
      },
      {
        id: 2,
        name: '할 일 목록 3',
        updatedAt: '2026-06-01',
        displayIndex: 2,
        date: '2026-06-01',
        commentCount: 3,
        deletedAt: null,
        description: '설명',
        doneAt: null,
        doneBy: null,
        frequency: 'ONCE',
        recurringId: 1,
        startDate: '2026-06-01',
        writer: {
          id: 0,
          image: '',
          nickname: '',
        },
      },
    ],
    createdAt: '2026-06-01',
    displayIndex: 0,
    groupId: 0,
    id: 0,
    name: '할 일 목록 1',
    updatedAt: '2026-06-01',
  },
  {
    tasks: [],
    createdAt: '2026-06-01',
    displayIndex: 1,
    groupId: 1,
    id: 1,
    name: '빈 할 일 목록',
    updatedAt: '2026-06-01',
  },
];